export BUNDLE_ID=com.turboblasterunlimited.k9karaoke
export TEAM_ID=TWVR9Z6AB2
export KEY_ID=2AJC6XDQVK
export KEY_CONTENTS="-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg2gGUhcOFsyOxvFJr
AWsOqwyvds0aMFMNpdDLI6vDdpWgCgYIKoZIzj0DAQehRANCAARL7gZaYncDnF13
pwqiyuu91fT7GPqm5Lf0stdZyBfu7LZOe+3e1UM11kMoWG2oI93YsJFV9IxjPb2y
3AV8rxdh
-----END PRIVATE KEY-----"